-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MIPS_tester IS
   PORT(
		reset, clock : OUT STD_LOGIC;
		-----------------------------------------------------------
		IsTEST : IN std_logic;
		sw_8_run : OUT std_logic; -- for IO
		sw_0_7 : OUT std_logic_vector(7 DOWNTO 0); --for IO
		HI_OUT : IN std_logic_vector(7 DOWNTO 0); -- for IO
		LO_OUT : IN std_logic_vector(7 DOWNTO 0); -- for IO
		addr_out : IN std_logic_vector(9 DOWNTO 0); -- for IO
		SEG0_OUT, SEG1_OUT : IN std_logic_vector(6 DOWNTO 0); -- for IO
		SEG2_OUT, SEG3_OUT : IN std_logic_vector(6 DOWNTO 0); -- for IO
		PORT_LEDG : IN std_logic_vector(7 DOWNTO 0);-- for IO
		PORT_LEDR : IN std_logic_vector(7 DOWNTO 0);-- for IO
		PC_plus_4_oout : IN STD_LOGIC_VECTOR(9 DOWNTO 0);
		isSpecial_out : IN STD_LOGIC;
		J_out : IN STD_LOGIC;
		Seven_Seg_out_top : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
		-----------------------------------------------------------
		-- Output important signals to pins for easy display in Simulator
		pc_oout : IN STD_LOGIC_VECTOR(9 DOWNTO 0);
		ALU_result_out, read_data_1_out, read_data_2_out, write_data_out, Instruction_out : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
		Branch_out, Zero_out, Memwrite_out, Regwrite_out : IN STD_LOGIC
   );

-- Declarations

END MIPS_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MIPS_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';


BEGIN

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '1', '0' AFTER 50 ns;
         WAIT FOR 100 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 1000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   reset <= mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '1',
         '0' AFTER 20 ns,
         '1' AFTER 120 ns;
      WAIT;
    END PROCESS u_1pulse_proc;

   -- Instance port mappings.

END struct;
